import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Commens/Navbar";
import Footer from "./Components/Commens/Footer";
import { Toaster } from "@/components/ui/sonner"
import Sider from "./Components/Commens/Sider";
import AuthProvider from "@/provider/auth-provider";
import CartProvider from "@/provider/cart-provider";
import WishlistProvider from "@/provider/wish-list-provider";
import UserInfoProvider from "@/provider/userInfo-provider";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
   icons: {
    icon: "https://freshcart-route.vercel.app/favicon.png",
  },title: "Fresh Chart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   
      <AuthProvider>
        <UserInfoProvider>
        <CartProvider>
          <WishlistProvider>
          <Sider/>
          <Navbar/>

        <div className="">
          {children}
          <Toaster position="top-center" richColors />
        </div>
        <Footer/>
        </WishlistProvider>
        </CartProvider>
        </UserInfoProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
